# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplinerating',
            name='device_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
